### ISSUE TITLE
feat: 3-2. 서류 평가하기 내 컴포넌트 구현

### ISSUE THREAD

**Issue by GraceKim527** [Cluting/cluting-frontend#48]
## 🛠 Issue

- 서류 평가하기 내 다음 3가지 컴포넌트를 구현합니다.

## 📝 To-do

- [x] 필터 및 정렬 드롭다운
- [x] 서류심사 과정 프로세스바 컴포넌트
- [ ] 서류심사 목록 컴포넌트
