### ISSUE TITLE
feat: 4-1 지원자 합불 결과 구현

### ISSUE THREAD

**Issue by yeonilil** [Cluting/cluting-frontend#68]
## 🛠 Issue

- 4-1 지원자 합불 결과 페이지를 구현합니다

## 📝 To-do

- [x] 4단계 프로세스 바 구현
- [x] 필터 구현(전체, 그룹)
- [x] 정렬 구현(가나다순, 지원순, 최신순)
- [x] 지원자 합불 영역 임시 데이터로 구현
