### ISSUE TITLE
feat: 4-3 합불 메시지 구현

### ISSUE THREAD

**Issue by yeonilil** [Cluting/cluting-frontend#70]
## 🛠 Issue

- 4-2 면접 일정 조절을 구현합니다

## 📝 To-do

- [x] 합격 메시지 작성 구현
- [x] 불합격 메시지 작성 구현
- [x] 합격 미리보기
- [x] 불합격 미리보기
- [x] 에러 케이스 구현
- [x] 4-3 완료 프로세스 구현 (완료 -> 하단 바 등장 -> 수정 버튼 전환)
- [x] 4단계 완료 프로세스 구현
