### ISSUE TITLE
rafactor: 4-3 합불 메시지 리팩토링 및 수정

### ISSUE THREAD

**Issue by yeonilil** [Cluting/cluting-frontend#76]
## 🛠 Issue

- 4-3 합불 메시지 리팩토링 및 수정합니다.

## 📝 To-do

- [x] 개별 정의 부분을 구현
- [x] 에러 합격, 불합격 전송 나누어 처리
- [x] 이미지 클릭 후 입력 가능하도록 수정
