### ISSUE TITLE
feat: 4단계 디자인 시안 반영, 리팩토링

### ISSUE THREAD

**Issue by yeonilil** [Cluting/cluting-frontend#80]
## 🛠 Issue

- 4-1, 4-3 디자인 시안 추가된 사항들을 반영합니다.

## 📝 To-do

- [x] 4-1 필터, 정렬 드롭다운 추가 
- [x] 전송하기 디자인 수정
- [x] 미리보기 디자인 수정 
- [x] 개별 정의 부분을 구현
- [x] 에러 합격, 불합격 전송 나누어 처리
- [x] 이미지 클릭 후 입력 가능하도록 수정
