### ISSUE TITLE
feat: 6-1 구현

### ISSUE THREAD

**Issue by yeonilil** [Cluting/cluting-frontend#86]
## 🛠 Issue

- 6-1 지원자 합불 결과를 구현합니다

## 📝 To-do

- [x] 필터, 정렬 기능 추가
- [x] 합격, 불합격자 표시
- [x] 그룹 없는 경우 처리
