### ISSUE TITLE
feat: 6-2 합불 안내 메시지 구현

### ISSUE THREAD

**Issue by yeonilil** [Cluting/cluting-frontend#88]
## 🛠 Issue

- 6-2 합불 안내 메시지 페이지를 구현합니다

## 📝 To-do

- [x] 합격 불합격 메시지 입력을 구현합니다
- [x] 개별 정의 기능을 구현합니다
- [x] 전송하기 , 미리보기 모달을 구현합니다 
- [x] 6단계 완료 처리를 구현합니다
