### ISSUE TITLE
refactor: 3-2 리팩토링

### ISSUE THREAD

**Issue by yeonilil** [Cluting/cluting-frontend#91]
## 🛠 Issue

- 3-2 리팩토링을 진행합니다

## 📝 To-do

- [ ] 필터 3-1 그룹과 연결 (기존 그룹 or 새로 생성한 그룹)
- [ ] 그룹 없는 경우 구현
- [x] 평가 전에서 클릭 시 각 서류 평가 페이지로 이동
- [x] 평가 상황 전역 상태 필요
- [x]  3-2 리스트 hover 스타일 추가 
- [x]  3-2 리스트 선택시 evaluation 동적 경로 처리 추가
- [ ]  리스트 무한 스크롤 구현
- [ ] 서류 평가 작성 도중 페이지 이탈 시 평가중 처리 
- [x] 각 평가마다 현재 운영자의 평가 상태 
- [x] 수정 가능, 열람 가능 파트에 따라 권한 부여 
- [ ] 합격 여부 결정 모달
- [ ] 합격 여부 결정 확인 모달 
- [ ] 하단 유도바 이의 제기 여부에 따라 다르게 구현
- [ ] 3단계 전체 완료 프로세스 구현
